### ISSUE TITLE
Day 4 part 2 gives wrong result for most inputs

### ISSUE THREAD

**Issue by LeMoonStar** [LeMoonStar/AoC20#2]
The result from Day 4 part 2 seems to almost always return a completely wrong result.
The previous solution to this problem as seen [here](https://github.com/LeMoonStar/AoC20/blob/ecc5dba2793bcf6394abde204eaf43261c6a7d16/src/day04/day04.cpp#L123) _(**just subtracting 1 from the result**)_ seemed to work on @LeMoonStar's input but **doesn't solve the problem on other inputs**. The problem most likely originates in a wrong regex pattern, but I was not able to find it yet.

**Comment by TrojanerHD** [comment]
In my first observation I found that the regex at https://github.com/LeMoonStar/AoC20/blob/ecc5dba2793bcf6394abde204eaf43261c6a7d16/src/day04/day04.cpp#L14 also includes the years 2000-2009 while iyr has to be at least 2010

**Comment by LeMoonStar** [comment]
> In my first observation I found that the regex at
> 
> https://github.com/LeMoonStar/AoC20/blob/ecc5dba2793bcf6394abde204eaf43261c6a7d16/src/day04/day04.cpp#L14
> also includes the years 2000-2009 while iyr has to be at least 2010

@networkException Pointed this out on discord too, but it didn't seem to change much when I corrected it. Tough, yeah, I should probably commit that fix. thanks for the reminder

**Comment by LeMoonStar** [comment]
Commit [5b972af](https://github.com/LeMoonStar/AoC20/commit/5b972afb011bc5b0a72c8523f67795943339b27b) fixed the issue.

**Comment by LeMoonStar** [comment]
> > In my first observation I found that the regex at
> > 
> > https://github.com/LeMoonStar/AoC20/blob/ecc5dba2793bcf6394abde204eaf43261c6a7d16/src/day04/day04.cpp#L14
> > also includes the years 2000-2009 while iyr has to be at least 2010
> 
> @networkException Pointed this out on discord too, but it didn't seem to change much when I corrected it. Tough, yeah, I should probably commit that fix. thanks for the reminder

The fix yesterday seemed to create even more problems, the cause for this seems to be that I forgot to add brackets on some regex patterns which broke them. the last commit (the one that fixed this issue) was basically the same I did yesterday but with brackets.
